### ISSUE TITLE
Placing of My Snippets plug-in window

### ISSUE THREAD

**Issue by DutchPete** [kinmury/Golden-Book#9]
I am using the plug-in *My Snippets*, which places a small icon in the status bar. When you click on it there is a window (or pop-up) that opens in the bottom right hand corner.

To be able to keep the status bar invisible and still use the plug-in, I have assigned a hotkey (⌃ ⌥ M) to open the plug-in. But when I use the hotkey the little window is opened in the top left corner. Huh?

**Comment by kinmury** [comment]
It make sense that it appears right there. Is that an issue? Since it not "displayed" visual nor in Obsidian, the only way the "MySnippet" Plugin would show up is in that corner specifically.

If you try the other settings, you would see that it shows the way in should, right next to the Status Bar.

I see that when you hover over it, the text shows in black, so I should fix it, besides that, I don't see an issue. 

Could to you give me an idea of where it should be? Or what should be happening? I mean, it work fine, and it does what it should given the circumstances.

**Comment by DutchPete** [comment]
Yes, the plug-in works absolutely fine with Golden Book.

Ah, I see where the misunderstanding comes from.

If you leave the status bar visible, then using the hotkey also brings up the My Snippets window in the bottom right corner.

If you hide the status bar, then use the hotkey, that little window suddenly appears in the top left corner, which is odd behaviour.

From my perspective, it would make more sense to have the window always appear in the same place: bottom right.

Still, this is no big deal so if you prefer not to spend time on this and perhaps leave it for later on, fine with me. 😀

**Comment by DutchPete** [comment]
> I see that when you hover over it, the text shows in black, so I should fix it

I tried the `obsidian.css` file from both the Latest Release and from the green Code button, but in neither is the black text fixed.

**Comment by kinmury** [comment]
I fixed the color issue now, let me know if there is something not quite right, since I don't use this plugin

**Comment by DutchPete** [comment]
Yep, that works. In the Outline pane though, it is still black when you hover over it.

**Comment by kinmury** [comment]
This issue should be fixed in the new version of the Theme, in case you have some trouble with it, I would like for you to open another issue, since this issue is titled for another one.
